### ISSUE TITLE
Can we perform captioning tasks on pedestrian images in reality to obtain finer grained text descriptions.

### ISSUE THREAD

**Issue by shams2023** [DavidMChan/caption-by-committee#12]
Can we perform captioning tasks on pedestrian images in reality to obtain finer grained text descriptions.
I have some real-life pedestrian images and I would like to generate corresponding text descriptions for them. I am not sure if your model can be implemented, and I look forward to your reply!
Thank you!

**Comment by DavidMChan** [comment]
It is likely that this will work for your problem, however it is hard to say exactly without additional detail (as our method can be applied to any standard image captioning approach). I encourage reading through [our paper](https://arxiv.org/pdf/2302.01328.pdf), and determining if it is applicable to your particular situation.
