### ISSUE TITLE
provide generated output

### ISSUE THREAD

**Issue by fawazsammani** [DavidMChan/caption-by-committee#4]
Hello and thanks for your work. Would it be possible to share the generated output from the LLM for the COCO dataset?

**Comment by DavidMChan** [comment]
Sure - here are the COCO val samples for both BLIP and OFA. Both of these files are JSON files (but I had to use the .txt file extension to get them to upload to github).

[output_coco_ofa.json.txt](https://github.com/DavidMChan/caption-by-committee/files/11509761/output_coco_ofa.json.txt)
[output_coco_blip.json.txt](https://github.com/DavidMChan/caption-by-committee/files/11509759/output_coco_blip.json.txt)

**Comment by fawazsammani** [comment]
Thank you very much! You have saved us loads of work for our project! We will make sure to greatly acknowledge and cite your work! 

Regards and have a great day!

**Comment by ryohachiuma** [comment]
@DavidMChan Thank you so much for releasing the processed file!

In the text files, how is the "reference_summary" sentence generated?
I cannot find the corresponding code in the repository. 
Also, what LLM is used to generate candidate_summary?

Thank you in advance!

**Comment by DavidMChan** [comment]
Hi @ryohachiuma - The reference summary is the summary of the COCO reference sentences (IC3 applied to human ground truths instead of candidates). The above JSON files use GPT 3 (Davinci).

**Comment by ryohachiuma** [comment]
@DavidMChan Thank you for your quick response!!
